[project]
name = "vcaml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "staveesh", email = "taveesh@uchicago.edu" }
]
requires-python = ">=3.11"
dependencies = [
    "dvc[s3,ssh]>=3.63.0",
    "fastapi>=0.117.0",
    "hydra-core>=1.3.2",
    "mlflow>=3.4.0",
    "polars>=1.33.1",
    "pyarrow>=21.0.0",
    "pydantic>=2.11.9",
    "scikit-learn>=1.7.2",
    "shap>=0.48.0",
    "rich",
    "uvicorn>=0.36.0",
    "xgboost>=3.0.5",
    "typer>=0.19.1",
    "pyyaml>=6.0.2",
    "tqdm>=4.67.1",
]

[project.scripts]
vcaml = "vcaml.cli:app"

[build-system]
requires = ["uv_build>=0.8.15,<0.9.0"]
build-backend = "uv_build"

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "anyio>=4.4",
    "pluggy>=1.5",
    "pytest>=8.1",
]
